### ISSUE TITLE
能否支持空密码登录?

### ISSUE THREAD

**Issue by shanquan** [newham/eftp#2]
内网设置了空密码，无法连接，提示必须输入密码或私钥😂

**Comment by newham** [comment]
空密码？还有这种操作吗？是不是设置的”无密码“登录。实际用的是私钥登录

**Comment by shanquan** [comment]
我开始以为是ftp://协议的应用，ftp连接可以设置用户密码为空。看了下源码，发现用的是node-ssh，实际是ssh和scp传输文件不是ftp协议（端口也不同），如果是ssh连接的话，密码或私钥就是必须的啦。

**Comment by shanquan** [comment]
我开始以为是ftp://协议的应用，ftp连接可以设置用户密码为空。看了下源码，发现用的是node-ssh，实际是ssh和scp传输文件不是ftp协议（端口也不同），如果是ssh连接的话，密码或私钥就是必须的啦。
